[project]
name = "raspibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-circuitpython-bno055>=5.4.20",
    "ahrs>=0.3.1",
    "flask>=3.1.1",
    "flask-socketio>=5.4.1",
    "langchain-core>=0.3.74",
    "langchain-ollama>=0.3.6",
    "langgraph>=0.6.4",
    "picamera2>=0.3.30",
    "sparkfun-qwiic-dual-encoder-reader>=0.0.2",
    "sparkfun-qwiic-icm20948>=2.0.1",
    "sparkfun-qwiic-otos>=2.0.0",
    "sparkfun-qwiic-scmd>=2.0.0",
]
